services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: uniweb
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - ./data/var/lib/mysql:/var/lib/mysql
    ports:
      - "3308:3306"
